-- init.sql
CREATE USER hive WITH PASSWORD 'hive';
CREATE DATABASE metastore OWNER hive;
CREATE SCHEMA AUTHORIZATION hive;

CREATE USER hue WITH PASSWORD 'hue';
CREATE DATABASE hue OWNER hue;
CREATE SCHEMA AUTHORIZATION hue;
